export const ItemData = [
  { id: 1, name: "Propane Gas Cylinder", category: "LPG" },
  { id: 2, name: "Butane Gas Cartridge", category: "LPG" },
  { id: 3, name: "Electric Drill", category: "Electricals" },
  { id: 4, name: "Extension Cord", category: "Electricals" },
  { id: 5, name: "USB Charging Cable", category: "Phone Accessories" },
  { id: 6, name: "Phone Case for iPhone 12", category: "Phone Accessories" },
  { id: 7, name: "LED Light Bulb", category: "Electricals" },
  { id: 8, name: "Portable Charger", category: "Phone Accessories" },
  { id: 9, name: "Screen Protector", category: "Phone Accessories" },
  { id: 10, name: "Wall Adapter", category: "Electricals" },
  { id: 11, name: "HDMI Cable", category: "Electricals" },
  { id: 12, name: "Surge Protector", category: "Electricals" },
  { id: 13, name: "Wireless Mouse", category: "Electricals" },
  { id: 14, name: "Bluetooth Speaker", category: "Electricals" },
  { id: 15, name: "Earphones", category: "Phone Accessories" },
];
